[SiteControl]
# MES API 地址
Endpoint=http://192.168.200.30:8001/api/cable/handleSiteControl
# 请求用的站点号
MySite=FDL

[Modbus]
Endpoint=192.168.1.10
BigEndian=true

[Report]
# 硬件上传原始数据的目录
WatchCsvDir=D:\MESDATA
# 生成报告需要的原始数据文件数
CsvCount=12
# 存放 OK 报告的目录
OkDir=D:\MESDATA\OK\
# 存放 NG 报告的目录
NgDir=D:\MESDATA\NG\

[LimitGroup1]
# 起始浮动力下限
InitialLowerLimit=
# 起始浮动力上限
InitialUpperLimit=
# 最终浮动力下限
FinalLowerLimit=
# 最终浮动力上限
FinalUpperLimit=

[LimitGroup2]
# 起始浮动力下限
InitialLowerLimit=
# 起始浮动力上限
InitialUpperLimit=
# 最终浮动力下限
FinalLowerLimit=
# 最终浮动力上限
FinalUpperLimit=
