<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<None Include="config.ini" CopyToOutputDirectory="PreserveNewest" />	
	<None Include="Hooks.cs" CopyToOutputDirectory="PreserveNewest" />	
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="FluentModbus" Version="5.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.10.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="8.0.0" />
  </ItemGroup>

</Project>
